spring:
  cloud:
    gateway:
      routes:
        - id: transaction
          uri: lb://TRANSACTION
          predicates:
            - Path=/transaction-api/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_IP:172.17.0.1}:${KEYCLOAK_PORT}/realms/finance-manager

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:${DISCOVERY_PORT}/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"

server:
  forward-headers-strategy: framework