apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keycloak.name }}
  labels:
    app: {{ .Chart.Name }}
    tier: {{ .Values.keycloak.name }}
spec:
  replicas: {{ .Values.keycloak.deployment.replicas }}
  selector:
    matchLabels:
      tier: {{ .Values.keycloak.name }}
  template:
    metadata:
      labels:
        tier: {{ .Values.keycloak.name }}
    spec:
      containers:
        - image: {{ .Values.keycloak.deployment.image }}
          name: {{ .Values.keycloak.name }}
          args:
            - start-dev
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.name }}
                  key: kc_bootstrap_admin_username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.name }}
                  key: kc_bootstrap_admin_password
            - name: KC_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.name }}
                  key: kc_db
            - name: KC_DB_URL
              value: jdbc:postgresql://{{ .Values.postgresql_db.name }}:{{ .Values.postgresql_db.inner_port }}/{{ .Values.postgresql_db.name }}
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql_db.name }}
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql_db.name }}
                  key: password
          ports:
            - containerPort: {{ .Values.keycloak.inner_port }}
              protocol: TCP
      restartPolicy: {{ .Values.keycloak.deployment.restartPolicy }}